# Generated by Django 5.2.5 on 2026-05-12 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MollyBackgroundColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='שם צבע')),
                ('hex_color', models.CharField(blank=True, help_text='קוד צבע ל-CSS, למשל "#ffffff". משמש לתצוגת דוגמית.', max_length=9, verbose_name='קוד HEX')),
                ('swatch_image', models.ImageField(blank=True, help_text='אופציונלי - תמונה קטנה שתוצג כדוגמית הצבע.', null=True, upload_to='molly_catalog/swatches/', verbose_name='תמונת דוגמית')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'צבע רקע',
                'verbose_name_plural': 'צבעי רקע',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MollyCatalogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='למשל: מולי', max_length=200, verbose_name='שם להצגה')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='טלפון')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='שם משתמש')),
                ('password_hash', models.CharField(max_length=128, verbose_name='סיסמא')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='כניסה אחרונה')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='פעילות אחרונה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'משתמש קטלוג מולי',
                'verbose_name_plural': 'משתמשי קטלוג מולי',
                'ordering': ('display_name', 'username'),
            },
        ),
        migrations.CreateModel(
            name='MollyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם קטגוריה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('image', models.ImageField(blank=True, null=True, upload_to='molly_catalog/categories/', verbose_name='תמונה')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'קטגוריה',
                'verbose_name_plural': 'קטגוריות',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MollyFabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='שם הבד')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'סוג בד',
                'verbose_name_plural': 'סוגי בדים',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MollyPrintDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='שם ההדפס')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('preview_image', models.ImageField(blank=True, help_text='תמונה של ההדפס שתוצג בבחירה.', null=True, upload_to='molly_catalog/prints/', verbose_name='תצוגת הדפס')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'הדפס',
                'verbose_name_plural': 'הדפסים',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MollyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'פעיל'), ('submitted', 'הוגש'), ('abandoned', 'נטוש')], default='active', max_length=20, verbose_name='סטטוס')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='molly_catalog.mollycataloguser', verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'עגלה',
                'verbose_name_plural': 'עגלות',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MollyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='מספר הזמנה')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('processing', 'בטיפול'), ('completed', 'הושלם'), ('cancelled', 'בוטל')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('notes', models.TextField(blank=True, verbose_name='הערות מולי')),
                ('admin_notes', models.TextField(blank=True, verbose_name='הערות פנימיות')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='molly_catalog.mollycart', verbose_name='עגלה מקורית')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='molly_catalog.mollycataloguser', verbose_name='לקוח')),
            ],
            options={
                'verbose_name': 'הזמנה',
                'verbose_name_plural': 'הזמנות',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='MollyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם מוצר')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('marketing_description', models.TextField(blank=True, help_text='טקסט קצר שמופיע בכרטיס המוצר.', verbose_name='תיאור שיווקי')),
                ('information', models.TextField(blank=True, help_text="מפרט / חומרים / הנחיות שטיפה וכד'.", verbose_name='מידע נוסף')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='molly_catalog/products/', verbose_name='תמונה ראשית')),
                ('is_orderable', models.BooleanField(default=True, help_text='האם מולי יכולה להזמין את המוצר.', verbose_name='זמין להזמנה')),
                ('has_variants', models.BooleanField(default=True, help_text='אם מסומן, מולי תבחר צבע/הדפס/בד. אחרת זה מוצר בודד.', verbose_name='יש לו ואריאנטים')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='השאר ריק כדי שהמוצר יופיע ישירות בעמוד הבית.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='molly_catalog.mollycategory', verbose_name='קטגוריה')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MollyProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='molly_catalog/products/gallery/', verbose_name='תמונה')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='טקסט חלופי')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='molly_catalog.mollyproduct', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'תמונת מוצר',
                'verbose_name_plural': 'תמונות מוצר',
                'ordering': ('order', 'created'),
            },
        ),
        migrations.CreateModel(
            name='MollyVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='אופציונלי - אם ריק נשתמש בתמונת המוצר.', null=True, upload_to='molly_catalog/variants/', verbose_name='תמונת ואריאנט')),
                ('sku', models.CharField(blank=True, help_text='לשימוש פנימי של מולי / אריה.', max_length=80, verbose_name='מק"ט פנימי')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('background_color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='molly_catalog.mollybackgroundcolor', verbose_name='צבע רקע')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='molly_catalog.mollyfabrictype', verbose_name='סוג בד')),
                ('print_design', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='molly_catalog.mollyprintdesign', verbose_name='הדפס')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='molly_catalog.mollyproduct', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'ואריאנט',
                'verbose_name_plural': 'ואריאנטים',
                'ordering': ('order', 'fabric_type__order', 'background_color__order', 'print_design__order'),
                'unique_together': {('product', 'background_color', 'print_design', 'fabric_type')},
            },
        ),
        migrations.CreateModel(
            name='MollyOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='שם מוצר')),
                ('background_color_name', models.CharField(blank=True, max_length=80, verbose_name='צבע רקע')),
                ('print_design_name', models.CharField(blank=True, max_length=150, verbose_name='הדפס')),
                ('fabric_type_name', models.CharField(blank=True, max_length=100, verbose_name='סוג בד')),
                ('variant_sku', models.CharField(blank=True, max_length=80, verbose_name='מק"ט')),
                ('quantity', models.PositiveIntegerField(verbose_name='כמות')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='molly_catalog.mollyorder', verbose_name='הזמנה')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='molly_catalog.mollyproduct', verbose_name='מוצר')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='molly_catalog.mollyvariant', verbose_name='ואריאנט')),
            ],
            options={
                'verbose_name': 'פריט הזמנה',
                'verbose_name_plural': 'פריטי הזמנה',
            },
        ),
        migrations.CreateModel(
            name='MollyCatalogUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='זמן')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='דפדפן')),
                ('page_url', models.CharField(max_length=500, verbose_name='דף')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='molly_catalog.mollycataloguser', verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'פעילות משתמש מולי',
                'verbose_name_plural': 'פעילויות משתמשי מולי',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='molly_catal_timesta_069c8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MollyCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='molly_catalog.mollycart', verbose_name='עגלה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='molly_catalog.mollyproduct', verbose_name='מוצר')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='molly_catalog.mollyvariant', verbose_name='ואריאנט')),
            ],
            options={
                'verbose_name': 'פריט בעגלה',
                'verbose_name_plural': 'פריטים בעגלה',
                'unique_together': {('cart', 'variant')},
            },
        ),
    ]
