# Generated by Django 5.2.5 on 2026-05-12 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molly_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MollyLabelColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='שם צבע תווית')),
                ('hex_color', models.CharField(blank=True, help_text='קוד צבע ל-CSS, למשל "#000000". משמש לתצוגת דוגמית.', max_length=9, verbose_name='קוד HEX')),
                ('swatch_image', models.ImageField(blank=True, null=True, upload_to='molly_catalog/label_swatches/', verbose_name='תמונת דוגמית')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'צבע תווית',
                'verbose_name_plural': 'צבעי תוויות',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='mollyorderitem',
            name='label_color_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='צבע תווית'),
        ),
        migrations.AddField(
            model_name='mollyvariant',
            name='default_label_color',
            field=models.ForeignKey(blank=True, help_text='צבע התווית שיוצרק עם הוואריאנט הזה. לא חלק מקומבינציות הואריאנטים.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='molly_catalog.mollylabelcolor', verbose_name='צבע תווית ברירת מחדל'),
        ),
    ]
