# Generated by Django 5.2.5 on 2026-05-12 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molly_catalog', '0002_mollylabelcolor_mollyorderitem_label_color_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mollycartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mollycartitem',
            name='selected_label_color',
            field=models.ForeignKey(blank=True, help_text='הצבע שמולי בחרה. אם ריק, ייעשה fallback לברירת המחדל של הוואריאנט.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='molly_catalog.mollylabelcolor', verbose_name='צבע תווית שנבחר'),
        ),
        migrations.AddField(
            model_name='mollyproduct',
            name='available_label_colors',
            field=models.ManyToManyField(blank=True, help_text='צבעי התווית שמולי תוכל לבחור מהם בעמוד המוצר. אם ריק - מולי תראה רק את צבע התווית של ברירת המחדל בלי אפשרות לשנות.', related_name='products', to='molly_catalog.mollylabelcolor', verbose_name='צבעי תווית זמינים לבחירה'),
        ),
        migrations.AlterUniqueTogether(
            name='mollycartitem',
            unique_together={('cart', 'variant', 'selected_label_color')},
        ),
    ]
