# Generated by Django 5.2.5 on 2026-06-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molly_catalog', '0003_alter_mollycartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mollycategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='mollyproduct',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
