# Generated by Django 5.2.12 on 2026-08-03 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molly_catalog', '0004_alter_mollycategory_slug_alter_mollyproduct_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MollyMockupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם מוצר')),
                ('image', models.ImageField(help_text='תמונת הבגד/המוצר שעליה תמוקם ההדפסה.', upload_to='molly_catalog/mockup_products/', verbose_name='תמונת מוצר')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'מוצר להדמיה',
                'verbose_name_plural': 'מוצרים להדמיה',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='MollyMockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, help_text='שם המוצר בזמן השמירה (נשמר גם אם המוצר נמחק).', max_length=200, verbose_name='שם המוצר')),
                ('print_image', models.ImageField(upload_to='molly_catalog/mockups/prints/', verbose_name='קובץ ההדפסה')),
                ('result_image', models.ImageField(upload_to='molly_catalog/mockups/results/', verbose_name='תמונת ההדמיה')),
                ('transform_data', models.JSONField(blank=True, default=dict, help_text='מיקום וגודל ההדפסה על המוצר (לעריכה עתידית).', verbose_name='נתוני מיקום')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='molly_catalog.mollycataloguser', verbose_name='משתמש')),
                ('mockup_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mockups', to='molly_catalog.mollymockupproduct', verbose_name='מוצר להדמיה')),
            ],
            options={
                'verbose_name': 'הדמיה',
                'verbose_name_plural': 'הדמיות',
                'ordering': ('-created',),
            },
        ),
    ]
