# Generated by Django 5.2.12 on 2026-08-03 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molly_catalog', '0005_mollymockupproduct_mollymockup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mollymockup',
            name='print_image',
            field=models.ImageField(blank=True, help_text='נשמר בהדמיות ישנות עם הדפסה אחת. הדמיות חדשות שומרות שכבות.', null=True, upload_to='molly_catalog/mockups/prints/', verbose_name='קובץ ההדפסה'),
        ),
        migrations.CreateModel(
            name='MollyMockupLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='molly_catalog/mockups/prints/', verbose_name='תמונת השכבה')),
                ('transform_data', models.JSONField(blank=True, default=dict, help_text='מיקום וגודל השכבה על המוצר (x, y, width).', verbose_name='נתוני מיקום')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר שכבה')),
                ('mockup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='molly_catalog.mollymockup', verbose_name='הדמיה')),
            ],
            options={
                'verbose_name': 'שכבת הדמיה',
                'verbose_name_plural': 'שכבות הדמיה',
                'ordering': ('order', 'id'),
            },
        ),
    ]
