# Generated by Django 5.2.12 on 2026-08-05 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molly_catalog', '0006_alter_mollymockup_print_image_mollymockuplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mollymockupproduct',
            name='real_width_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='רוחב אזור ההדפסה על הבגד בס״מ — כפי שמוצג ברוחב התמונה. לדוגמה: גוף קצר ברוחב 40 ס״מ → הזן 40. נדרש לייצוא הדפסה 1:1.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)], verbose_name='רוחב פיזי (ס״מ)'),
        ),
    ]
