# Generated by Django 5.2.12 on 2026-08-06 11:21

import molly_catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molly_catalog', '0007_mollymockupproduct_real_width_cm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mollymockup',
            name='print_image',
            field=models.ImageField(blank=True, help_text='נשמר בהדמיות ישנות עם הדפסה אחת. הדמיות חדשות שומרות שכבות.', null=True, upload_to=molly_catalog.models.mockup_print_upload_to, verbose_name='קובץ ההדפסה'),
        ),
        migrations.AlterField(
            model_name='mollymockup',
            name='result_image',
            field=models.ImageField(upload_to=molly_catalog.models.mockup_result_upload_to, verbose_name='תמונת ההדמיה'),
        ),
        migrations.AlterField(
            model_name='mollymockuplayer',
            name='image',
            field=models.ImageField(upload_to=molly_catalog.models.mockup_print_upload_to, verbose_name='תמונת השכבה'),
        ),
    ]
