# Generated by Django 5.2.12 on 2026-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molly_catalog', '0008_unique_mockup_image_upload_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='mollymockup',
            name='name',
            field=models.CharField(blank=True, help_text='שם שהמשתמשת נתנה להדמיה בשמירה.', max_length=200, verbose_name='שם ההדמיה'),
        ),
    ]
