# Generated by Django 5.2.12 on 2026-09-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molly_catalog', '0009_mollymockup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mollyproduct',
            name='sale_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='מחיר ליחידה בשקלים — לא כולל מע"מ. מוצג באדמין בלבד; מולי לא רואה.',
                max_digits=10,
                null=True,
                verbose_name='מחיר סיטונאי (לא כולל מע"מ)',
            ),
        ),
        migrations.AddField(
            model_name='mollyorderitem',
            name='unit_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='מחיר שנסגר בזמן ההזמנה. מולי לא רואה.',
                max_digits=10,
                null=True,
                verbose_name='מחיר ליחידה (לא כולל מע"מ)',
            ),
        ),
        migrations.AddField(
            model_name='mollyorderitem',
            name='line_total',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name='סה"כ שורה (לא כולל מע"מ)',
            ),
        ),
    ]
