# Generated by Django 5.2.5 on 2025-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional overall gallery title', max_length=120)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('caption1', models.CharField(blank=True, max_length=120)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('caption2', models.CharField(blank=True, max_length=120)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('caption3', models.CharField(blank=True, max_length=120)),
                ('image4', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('caption4', models.CharField(blank=True, max_length=120)),
                ('image5', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('caption5', models.CharField(blank=True, max_length=120)),
                ('image6', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('caption6', models.CharField(blank=True, max_length=120)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'גלריה',
                'verbose_name_plural': 'גלריות',
            },
        ),
    ]
