# Generated by Django 5.2.4 on 2025-08-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='תמונת באנר רקע (אופציונלי)', null=True, upload_to='banner/')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'באנר',
                'verbose_name_plural': 'באנרים',
            },
        ),
    ]
