# Generated by Django 5.2.4 on 2025-08-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, help_text='תיאור (אפשר למחוק שדה זה בהמשך)', max_length=120),
        ),
    ]
