# Generated by Django 5.2.4 on 2025-08-11 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_banner_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
    ]
