# Generated by Django 5.2.5 on 2025-08-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_banner_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='שם מלא')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='חברה')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='טלפון')),
                ('message', models.TextField(blank=True, verbose_name='תיאור הבקשה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answered', models.BooleanField(default=False, verbose_name='טופל')),
            ],
            options={
                'verbose_name': 'פניית יצירת קשר',
                'verbose_name_plural': 'פניות יצירת קשר',
                'ordering': ('-created',),
            },
        ),
    ]
