# Generated by Django 5.2.5 on 2025-08-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='תמונה')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'תמונת סליידר',
                'verbose_name_plural': 'תמונות סליידר',
                'ordering': ('order', 'id'),
            },
        ),
    ]
