# Generated by Django 5.2.5 on 2025-08-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='caption1',
            field=models.CharField(blank=True, help_text='הטקסט שמופיע על התמונה', max_length=120, verbose_name='שם קטגוריה 1'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='caption2',
            field=models.CharField(blank=True, help_text='הטקסט שמופיע על התמונה', max_length=120, verbose_name='שם קטגוריה 2'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='caption3',
            field=models.CharField(blank=True, help_text='הטקסט שמופיע על התמונה', max_length=120, verbose_name='שם קטגוריה 3'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='caption4',
            field=models.CharField(blank=True, help_text='הטקסט שמופיע על התמונה', max_length=120, verbose_name='שם קטגוריה 4'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='caption5',
            field=models.CharField(blank=True, help_text='הטקסט שמופיע על התמונה', max_length=120, verbose_name='שם קטגוריה 5'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='caption6',
            field=models.CharField(blank=True, help_text='הטקסט שמופיע על התמונה', max_length=120, verbose_name='שם קטגוריה 6'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='תמונה 1'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='תמונה 2'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='תמונה 3'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='תמונה 4'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='תמונה 5'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/', verbose_name='תמונה 6'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(blank=True, help_text='כותרת כללית לגלריה (אופציונלי)', max_length=120, verbose_name='כותרת (לא חובה)'),
        ),
    ]
