# Generated by Django 5.2.4 on 2025-08-29 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_gallery_caption1_alter_gallery_caption2_and_more'),
        ('main', '0007_banner_page'),
    ]

    operations = [
    ]
