# Generated by Django 5.2.5 on 2025-08-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_gallery_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='height_variant',
            field=models.CharField(choices=[('auto', 'אוטומטי'), ('tall', 'גבוה'), ('short', 'נמוך')], default='auto', help_text='בחרו גובה הבאנר: אוטומטי לפי עמוד, או ציינו גבוה/נמוך ידנית', max_length=12, verbose_name='גובה'),
        ),
    ]
