# Generated by Django 5.2.5 on 2025-08-29 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_brandinggallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'גלריית דף הבית', 'verbose_name_plural': 'גלריית דף הבית קרוסלה'},
        ),
    ]
