# Generated by Django 5.2.5 on 2025-08-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_printinggallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printinggallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
