# Generated by Django 5.2.5 on 2025-08-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_fabricsgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricsgallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
