# Generated by Django 5.2.5 on 2025-08-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_manufacturinggallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturinggallery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
