# Generated by Django 5.2.4 on 2025-08-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_manufacturinggallery_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_display', models.CharField(blank=True, help_text='לדוגמה: 054-2367535', max_length=40, verbose_name='טלפון להצגה')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='אימייל')),
                ('whatsapp_link', models.URLField(blank=True, help_text='לדוגמה: https://wa.me/9725...', verbose_name='קישור וואטסאפ')),
                ('instagram_url', models.URLField(blank=True, verbose_name='קישור אינסטגרם')),
                ('facebook_url', models.URLField(blank=True, verbose_name='קישור פייסבוק')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'הגדרות פוטר',
                'verbose_name_plural': 'הגדרות פוטר',
            },
        ),
    ]
