# Generated by Django 5.2.4 on 2025-08-30 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_footersettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'גלריית דף הבית', 'verbose_name_plural': 'גלריית דף הבית'},
        ),
    ]
