# Generated by Django 5.2.5 on 2025-09-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_photosgallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה 5')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה 6')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה 7')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה 8')),
                ('image9', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה 9')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'גלריית גזירה',
                'verbose_name_plural': 'גלריות גזירה',
            },
        ),
        migrations.AlterModelOptions(
            name='patternmakinggallery',
            options={'verbose_name': 'גלריית תדמיתנות', 'verbose_name_plural': 'גלריות תדמיתנות'},
        ),
    ]
