# Generated by Django 5.2.5 on 2025-09-05 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_cuttinggallery_alter_patternmakinggallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='branding_gallery/', verbose_name='תמונה')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.brandinggallery')),
            ],
            options={
                'verbose_name': 'תמונה למיתוג',
                'verbose_name_plural': 'תמונות מיתוג',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CuttingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cutting_gallery/', verbose_name='תמונה')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.cuttinggallery')),
            ],
            options={
                'verbose_name': 'תמונה לגזירה',
                'verbose_name_plural': 'תמונות גזירה',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FabricsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fabrics_gallery/', verbose_name='תמונה')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.fabricsgallery')),
            ],
            options={
                'verbose_name': 'תמונה לבדים',
                'verbose_name_plural': 'תמונות בדים',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManufacturingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='manufacturing_gallery/', verbose_name='תמונה')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.manufacturinggallery')),
            ],
            options={
                'verbose_name': 'תמונה לייצור',
                'verbose_name_plural': 'תמונות ייצור',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatternmakingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='patternmaking_gallery/', verbose_name='תמונה')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.patternmakinggallery')),
            ],
            options={
                'verbose_name': 'תמונה לתדמיתנות',
                'verbose_name_plural': 'תמונות תדמיתנות',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhotosImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos_gallery/', verbose_name='תמונה')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.photosgallery')),
            ],
            options={
                'verbose_name': 'תמונה לגלריית תמונות',
                'verbose_name_plural': 'תמונות לגלריית תמונות',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=150, verbose_name='ALT')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='printing_gallery/', verbose_name='תמונה')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.printinggallery')),
            ],
            options={
                'verbose_name': 'תמונה להדפסות',
                'verbose_name_plural': 'תמונות הדפסות',
                'ordering': ('order', 'id'),
                'abstract': False,
            },
        ),
    ]
