# Generated by Django 5.2.5 on 2025-09-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_brandingimage_cuttingimage_fabricsimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='video',
            field=models.FileField(blank=True, help_text='וידיאו באנר (אופציונלי) - יתעדף על פני תמונה', null=True, upload_to='banner/videos/'),
        ),
    ]
