# Generated by Django 5.2.4 on 2025-10-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_banner_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='תמונת באנר רקע (אופציונלי) - גיבוי לוידיאו', null=True, upload_to='banner/'),
        ),
    ]
