# Generated by Django 5.0 on 2026-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_add_video_field_to_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='info_image',
            field=models.ImageField(blank=True, help_text="התמונה שמופיעה בסקשן 'מי אנחנו' בדף הבית", null=True, upload_to='gallery/', verbose_name='תמונת מי אנחנו'),
        ),
    ]
