# Generated by Django 5.2.4 on 2025-11-15 04:44

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteCatalogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='שם העסק')),
                ('contact_name', models.CharField(max_length=200, verbose_name='שם איש קשר')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='טלפון איש קשר')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='שם משתמש')),
                ('password_hash', models.CharField(max_length=128, verbose_name='סיסמא')),
                ('is_active', models.BooleanField(default=True, help_text='האם המשתמש יכול להתחבר', verbose_name='פעיל')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'משתמש קטלוג לבן',
                'verbose_name_plural': 'משתמשי קטלוג לבן',
                'ordering': ('company_name', 'username'),
            },
        ),
        migrations.CreateModel(
            name='WhiteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם קטגוריה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('image', models.ImageField(blank=True, null=True, upload_to='white_catalog/categories/', verbose_name='תמונה')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('slug', models.SlugField(blank=True, help_text='יוצר אוטומטית מהשם', max_length=200, unique=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'קטגוריה לבנה',
                'verbose_name_plural': 'קטגוריות לבנות',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WhiteSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם תת-קטגוריה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('marketing_description', tinymce.models.HTMLField(blank=True, help_text='תיאור שיווקי של המוצר', verbose_name='תיאור שיווקי')),
                ('information', tinymce.models.HTMLField(blank=True, help_text='מידע כללי על המוצר', verbose_name='מידע')),
                ('pattern_and_branding', tinymce.models.HTMLField(blank=True, help_text='פרטים על דפוס ומיתוג', verbose_name='דפוס ומיתוג')),
                ('fabric_production', tinymce.models.HTMLField(blank=True, help_text='אפשרויות ייצור בדים', verbose_name='אפשרות ייצור בדים')),
                ('sizes', tinymce.models.HTMLField(blank=True, help_text='מידות זמינות למוצר', verbose_name='מידות')),
                ('image', models.ImageField(blank=True, help_text='תמונה ראשית - מוצגת בכרטיס התת-קטגוריה', null=True, upload_to='white_catalog/subcategories/', verbose_name='תמונה ראשית')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('slug', models.SlugField(blank=True, help_text='יוצר אוטומטית מהשם', max_length=200, unique=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='השאר ריק אם תרצה שהתת-קטגוריה תופיע כקטגוריה בעמוד הראשי', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='white_catalog.whitecategory', verbose_name='קטגוריה')),
            ],
            options={
                'verbose_name': 'תת-קטגוריה לבנה',
                'verbose_name_plural': 'תת-קטגוריות לבנות',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='WhiteSubcategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='white_catalog/subcategories/gallery/', verbose_name='תמונה')),
                ('alt_text', models.CharField(blank=True, help_text='תיאור התמונה - מומלץ למילוי', max_length=200, verbose_name='טקסט חלופי')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='white_catalog.whitesubcategory', verbose_name='תת-קטגוריה')),
            ],
            options={
                'verbose_name': 'תמונת תת-קטגוריה לבנה',
                'verbose_name_plural': 'תמונות תת-קטגוריה לבנה',
                'ordering': ('order', 'created'),
            },
        ),
    ]
