# Generated by Django 5.2.4 on 2025-11-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitesubcategory',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='מחיר ליחידה (₪)', max_digits=10, null=True, verbose_name='מחיר ליחידה'),
        ),
    ]
