# Generated by Django 5.2.4 on 2025-11-18 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0002_whitesubcategory_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitesubcategory',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='מחיר ליחידה בשקלים - לא כולל מע"מ', max_digits=10, null=True, verbose_name='מחיר ליחידה (לא כולל מע"מ)'),
        ),
        migrations.CreateModel(
            name='WhiteSubcategoryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(help_text='למשל: S, M, L, XL, 2-4, 6-8', max_length=50, verbose_name='שם המידה')),
                ('price', models.DecimalField(decimal_places=2, help_text='מחיר למידה זו בשקלים - לא כולל מע"מ', max_digits=10, verbose_name='מחיר (לא כולל מע"מ)')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_prices', to='white_catalog.whitesubcategory', verbose_name='תת-קטגוריה')),
            ],
            options={
                'verbose_name': 'מחיר למידה',
                'verbose_name_plural': 'מחירים למידות',
                'ordering': ('order', 'id'),
            },
        ),
    ]
