# Generated by Django 5.2.4 on 2025-11-23 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0003_alter_whitesubcategory_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitecataloguser',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='פעילות אחרונה'),
        ),
        migrations.AddField(
            model_name='whitecataloguser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='כניסה אחרונה'),
        ),
        migrations.CreateModel(
            name='WhiteCatalogUserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='זמן')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='כתובת IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='דפדפן')),
                ('page_url', models.CharField(max_length=500, verbose_name='דף')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='white_catalog.whitecataloguser', verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'פעילות משתמש',
                'verbose_name_plural': 'פעילויות משתמשים',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['-timestamp', 'user'], name='white_catal_timesta_0e1e62_idx')],
            },
        ),
    ]
