# Generated by Django 5.2.5 on 2025-11-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0004_whitecataloguser_last_activity_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitesubcategory',
            name='online_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='מחיר מומלץ למכירה באתר החנות ללקוח הסופי - לא כולל מע"מ', max_digits=10, null=True, verbose_name='מחיר קמעונאי מומלץ (לא כולל מע"מ)'),
        ),
        migrations.AlterField(
            model_name='whitesubcategory',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='מחיר סיטונאי בשקלים - לא כולל מע"מ', max_digits=10, null=True, verbose_name='מחיר סיטונאי (לא כולל מע"מ)'),
        ),
    ]
