# Generated by Django 5.2.5 on 2026-03-31 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0005_whitesubcategory_online_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitePackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='למשל: מארז שלישיות, מארז חמישיות', max_length=100, verbose_name='שם מארז')),
                ('quantity', models.PositiveIntegerField(help_text='למשל: 3 או 5', verbose_name='כמות יחידות במארז')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'סוג מארז',
                'verbose_name_plural': 'סוגי מארזים',
                'ordering': ('order', 'quantity'),
            },
        ),
        migrations.AddField(
            model_name='whitesubcategory',
            name='is_orderable',
            field=models.BooleanField(default=False, help_text='האם מוצר זה נכלל במערכת ההזמנות (גרסאות + מארזים)', verbose_name='זמין להזמנה'),
        ),
        migrations.CreateModel(
            name='WhiteCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'פעיל'), ('submitted', 'הוגש'), ('abandoned', 'נטוש')], default='active', max_length=20, verbose_name='סטטוס')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='white_catalog.whitecataloguser', verbose_name='משתמש')),
            ],
            options={
                'verbose_name': 'עגלת קניות',
                'verbose_name_plural': 'עגלות קניות',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='WhiteOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='מספר הזמנה')),
                ('status', models.CharField(choices=[('pending', 'ממתין לאישור'), ('confirmed', 'אושר'), ('processing', 'בטיפול'), ('shipped', 'נשלח'), ('delivered', 'נמסר'), ('cancelled', 'בוטל')], default='pending', max_length=20, verbose_name='סטטוס')),
                ('notes', models.TextField(blank=True, verbose_name='הערות לקוח')),
                ('admin_notes', models.TextField(blank=True, verbose_name='הערות פנימיות')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='סה"כ (לא כולל מע"מ)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='white_catalog.whitecart', verbose_name='עגלה מקורית')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='white_catalog.whitecataloguser', verbose_name='לקוח')),
            ],
            options={
                'verbose_name': 'הזמנה',
                'verbose_name_plural': 'הזמנות',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='WhiteProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='למשל: טריקו, פלנל, כותנה', max_length=100, verbose_name='שם חומר/גרסה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='white_catalog.whitesubcategory', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'גרסת מוצר',
                'verbose_name_plural': 'גרסאות מוצר',
                'ordering': ('order', 'name'),
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WhiteOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='שם מוצר')),
                ('variant_name', models.CharField(max_length=100, verbose_name='גרסה')),
                ('size_name', models.CharField(max_length=50, verbose_name='מידה')),
                ('pack_type_name', models.CharField(max_length=100, verbose_name='סוג מארז')),
                ('pack_quantity', models.PositiveIntegerField(verbose_name='יחידות במארז')),
                ('quantity', models.PositiveIntegerField(verbose_name='כמות מארזים')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר למארז (לא כולל מע"מ)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='white_catalog.whiteorder', verbose_name='הזמנה')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='white_catalog.whitesubcategory', verbose_name='מוצר')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='white_catalog.whiteproductvariant', verbose_name='גרסה')),
            ],
            options={
                'verbose_name': 'פריט הזמנה',
                'verbose_name_plural': 'פריטי הזמנה',
            },
        ),
        migrations.CreateModel(
            name='WhiteVariantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(help_text='למשל: 0-3, 3-6, 6-12, 12-18, 18-24', max_length=50, verbose_name='מידה')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='white_catalog.whiteproductvariant', verbose_name='גרסה')),
            ],
            options={
                'verbose_name': 'מידה לגרסה',
                'verbose_name_plural': 'מידות לגרסה',
                'ordering': ('order', 'id'),
                'unique_together': {('variant', 'size_name')},
            },
        ),
        migrations.CreateModel(
            name='WhiteVariantPackPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='מחיר למארז בשקלים — לא כולל מע"מ', max_digits=10, verbose_name='מחיר (לא כולל מע"מ)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pack_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_prices', to='white_catalog.whitepacktype', verbose_name='סוג מארז')),
                ('variant_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_prices', to='white_catalog.whitevariantsize', verbose_name='מידה')),
            ],
            options={
                'verbose_name': 'מחיר מארז לפי מידה',
                'verbose_name_plural': 'מחירי מארזים לפי מידה',
                'unique_together': {('variant_size', 'pack_type')},
            },
        ),
        migrations.CreateModel(
            name='WhiteCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='כמות מארזים')),
                ('price_at_add', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='מחיר בעת הוספה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='white_catalog.whitecart', verbose_name='עגלה')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='white_catalog.whitesubcategory', verbose_name='מוצר')),
                ('pack_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='white_catalog.whitepacktype', verbose_name='סוג מארז')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='white_catalog.whiteproductvariant', verbose_name='גרסה')),
                ('variant_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='white_catalog.whitevariantsize', verbose_name='מידה')),
            ],
            options={
                'verbose_name': 'פריט בעגלה',
                'verbose_name_plural': 'פריטים בעגלה',
                'unique_together': {('cart', 'variant_size', 'pack_type')},
            },
        ),
    ]
