# Generated by Django 5.2.12 on 2026-04-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0011_split_order_flags_and_simple_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whitesubcategory',
            options={'ordering': ('order', 'name'), 'verbose_name': 'מוצר', 'verbose_name_plural': 'מוצרים'},
        ),
        migrations.AlterField(
            model_name='whitefabrictype',
            name='description',
            field=models.TextField(blank=True, help_text='הרכב הבד, עונתיות, תכונות...', verbose_name='תיאור הבד'),
        ),
        migrations.AlterField(
            model_name='whitefabrictype',
            name='name',
            field=models.CharField(help_text="למשל: טריקו ג'רזי, פלנל, כותנה", max_length=100, unique=True, verbose_name='שם הבד'),
        ),
        migrations.AlterField(
            model_name='whitesizetype',
            name='name',
            field=models.CharField(help_text='למשל: 0-3, 3-6, 6-12, 12-18, 18-24', max_length=50, unique=True, verbose_name='שם מידה'),
        ),
    ]
