# Generated by Django 5.2.12 on 2026-04-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0013_whitesubcategory_simple_price_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitecategory',
            name='show_products_on_homepage',
            field=models.BooleanField(default=False, help_text='אם מסומן, בדף הבית יוצגו המוצרים של הקטגוריה במקום כרטיס הקטגוריה עצמה', verbose_name='הצג מוצרים בדף הבית'),
        ),
    ]
