# Generated by Django 5.2.12 on 2026-06-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0014_whitecategory_show_products_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitecataloguser',
            name='pack_route',
            field=models.CharField(choices=[('both', 'גם שלישיות וגם חמישיות'), ('threes', 'שלישיות בלבד'), ('fives', 'חמישיות בלבד')], default='both', help_text='אילו צורות אריזה המשתמש יראה בקטלוג', max_length=10, verbose_name='מסלול מוצרים'),
        ),
        migrations.AddField(
            model_name='whiteproductvariant',
            name='pack_types',
            field=models.ManyToManyField(blank=True, help_text='באילו מארזים הגרסה נמכרת. ריק = כל המארזים', related_name='variants', to='white_catalog.whitepacktype', verbose_name='צורת אריזה'),
        ),
    ]
