# Generated by Django 5.2.12 on 2026-06-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0016_populate_variant_pack_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='whiteproductvariant',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ברקוד'),
        ),
    ]
