# Generated by Django 5.2.12 on 2026-07-07 06:40

from django.db import migrations, models


def normalize_barcodes(apps, schema_editor):
    """Convert empty/whitespace barcodes to NULL and fail loudly on existing duplicates."""
    WhiteProductVariant = apps.get_model("white_catalog", "WhiteProductVariant")

    for variant in WhiteProductVariant.objects.exclude(barcode__isnull=True):
        normalized = (variant.barcode or "").strip() or None
        if normalized != variant.barcode:
            variant.barcode = normalized
            variant.save(update_fields=["barcode"])

    duplicates = (
        WhiteProductVariant.objects.filter(barcode__isnull=False)
        .values("barcode")
        .annotate(cnt=models.Count("id"))
        .filter(cnt__gt=1)
    )
    if duplicates:
        dupe_list = ", ".join(f"{d['barcode']} (x{d['cnt']})" for d in duplicates)
        raise RuntimeError(
            f"לא ניתן להוסיף אילוץ ייחודיות — קיימים ברקודים כפולים: {dupe_list}. "
            "נקה את הכפילויות באדמין והרץ את המיגרציה שוב."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0017_whiteproductvariant_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whiteproductvariant',
            name='barcode',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='ברקוד'),
        ),
        migrations.RunPython(normalize_barcodes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='whiteproductvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('barcode',), name='unique_variant_barcode', violation_error_message='ברקוד זה כבר קיים בגרסת מוצר אחרת'),
        ),
    ]
