# Generated by Django 5.2.12 on 2026-07-27 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('white_catalog', '0018_alter_whiteproductvariant_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='למשל: לבן, תכלת, ורוד עתיק', max_length=80, unique=True, verbose_name='שם צבע')),
                ('hex_color', models.CharField(blank=True, help_text='קוד צבע ל-CSS, למשל "#ffffff" — משמש לתצוגת הדוגמית', max_length=9, verbose_name='קוד HEX')),
                ('swatch_image', models.ImageField(blank=True, help_text='אופציונלי — תמונה קטנה שתוצג כדוגמית במקום צבע אחיד', null=True, upload_to='white_catalog/color_swatches/', verbose_name='תמונת דוגמית')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'צבע (מניפה)',
                'verbose_name_plural': 'מניפת צבעים',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.AddField(
            model_name='whiteorderitem',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='ברקוד'),
        ),
        migrations.AddField(
            model_name='whiteorderitem',
            name='color_name',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='צבע'),
        ),
        migrations.AddField(
            model_name='whitesubcategory',
            name='has_color_variants',
            field=models.BooleanField(default=False, help_text='סמן אם המוצר מוזמן דרך מניפת צבעים (לכל צבע ברקוד משלו). לא לשלב עם גרסאות + מארזים', verbose_name='הזמנה לפי מניפת צבעים'),
        ),
        migrations.CreateModel(
            name='WhiteColorVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, verbose_name='ברקוד')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='אם ריק — ייעשה שימוש במחיר הסיטונאי של המוצר', max_digits=10, null=True, verbose_name='מחיר ליחידה (לא כולל מע"מ)')),
                ('image', models.ImageField(blank=True, help_text='אופציונלי — בחירת הצבע בעמוד המוצר תחליף את התמונה הראשית', null=True, upload_to='white_catalog/color_variants/', verbose_name='תמונת צבע')),
                ('is_active', models.BooleanField(default=True, verbose_name='פעיל')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='סדר תצוגה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='white_catalog.whitecolor', verbose_name='צבע')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variants', to='white_catalog.whitesubcategory', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'צבע למוצר',
                'verbose_name_plural': 'צבעים למוצר',
                'ordering': ('order', 'color__order', 'color__name'),
            },
        ),
        migrations.AddField(
            model_name='whitecartitem',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='white_catalog.whitecolorvariant', verbose_name='צבע'),
        ),
        migrations.AddField(
            model_name='whiteorderitem',
            name='color_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='white_catalog.whitecolorvariant', verbose_name='צבע'),
        ),
        migrations.AddConstraint(
            model_name='whitecartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('color_variant__isnull', False)), fields=('cart', 'color_variant'), name='unique_cart_color_variant'),
        ),
        migrations.AddConstraint(
            model_name='whitecolorvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False), models.Q(('barcode', ''), _negated=True)), fields=('barcode',), name='unique_color_variant_barcode', violation_error_message='ברקוד זה כבר קיים בצבע מוצר אחר'),
        ),
        migrations.AlterUniqueTogether(
            name='whitecolorvariant',
            unique_together={('product', 'color')},
        ),
    ]
