# Generated by Django 5.2.4 on 2025-11-05 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם קטגוריה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/categories/', verbose_name='תמונה')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('slug', models.SlugField(blank=True, help_text='יוצר אוטומטית מהשם', max_length=200, unique=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'קטגוריה',
                'verbose_name_plural': 'קטגוריות',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם תת-קטגוריה')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/subcategories/', verbose_name='תמונה')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('slug', models.SlugField(blank=True, help_text='יוצר אוטומטית מהשם', max_length=200, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='קטגוריה')),
            ],
            options={
                'verbose_name': 'תת-קטגוריה',
                'verbose_name_plural': 'תת-קטגוריות',
                'ordering': ('order', 'name'),
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם מוצר')),
                ('description', models.TextField(blank=True, verbose_name='תיאור')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/products/', verbose_name='תמונה')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('is_active', models.BooleanField(default=True, help_text='האם להציג את המוצר בקטלוג', verbose_name='פעיל')),
                ('slug', models.SlugField(blank=True, help_text='יוצר אוטומטית מהשם', max_length=200, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.subcategory', verbose_name='תת-קטגוריה')),
            ],
            options={
                'verbose_name': 'מוצר',
                'verbose_name_plural': 'מוצרים',
                'ordering': ('order', 'name'),
                'unique_together': {('subcategory', 'slug')},
            },
        ),
    ]
