# Generated by Django 5.2.4 on 2025-11-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='שם העסק')),
                ('contact_name', models.CharField(max_length=200, verbose_name='שם איש קשר')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='טלפון איש קשר')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='שם משתמש')),
                ('password_hash', models.CharField(max_length=128, verbose_name='סיסמא')),
                ('is_active', models.BooleanField(default=True, help_text='האם המשתמש יכול להתחבר', verbose_name='פעיל')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'משתמש קטלוג',
                'verbose_name_plural': 'משתמשי קטלוג',
                'ordering': ('company_name', 'username'),
            },
        ),
    ]
