# Generated by Django 5.2.4 on 2025-11-10 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_cataloguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='תמונה ראשית - מוצגת בכרטיס המוצר', null=True, upload_to='catalog/products/', verbose_name='תמונה ראשית'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/products/gallery/', verbose_name='תמונה')),
                ('alt_text', models.CharField(blank=True, help_text='תיאור התמונה - מומלץ למילוי', max_length=200, verbose_name='טקסט חלופי')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product', verbose_name='מוצר')),
            ],
            options={
                'verbose_name': 'תמונת מוצר',
                'verbose_name_plural': 'תמונות מוצר',
                'ordering': ('order', 'created'),
            },
        ),
    ]
