# Generated by Django 5.2.4 on 2025-11-11 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, help_text='תמונה ראשית - מוצגת בכרטיס התת-קטגוריה', null=True, upload_to='catalog/subcategories/', verbose_name='תמונה ראשית'),
        ),
        migrations.CreateModel(
            name='SubcategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/subcategories/gallery/', verbose_name='תמונה')),
                ('alt_text', models.CharField(blank=True, help_text='תיאור התמונה - מומלץ למילוי', max_length=200, verbose_name='טקסט חלופי')),
                ('order', models.PositiveIntegerField(default=0, help_text='מספר קטן = קודם', verbose_name='סדר תצוגה')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.subcategory', verbose_name='תת-קטגוריה')),
            ],
            options={
                'verbose_name': 'תמונת תת-קטגוריה',
                'verbose_name_plural': 'תמונות תת-קטגוריה',
                'ordering': ('order', 'created'),
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
