# Generated by Django 5.2.5 on 2025-11-11 11:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_productimage_product_alter_subcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='fabric_production',
            field=tinymce.models.HTMLField(blank=True, help_text='אפשרויות ייצור בדים', verbose_name='אפשרות ייצור בדים'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='information',
            field=tinymce.models.HTMLField(blank=True, help_text='מידע כללי על המוצר', verbose_name='מידע'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='marketing_description',
            field=tinymce.models.HTMLField(blank=True, help_text='תיאור שיווקי של המוצר', verbose_name='תיאור שיווקי'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='pattern_and_branding',
            field=tinymce.models.HTMLField(blank=True, help_text='פרטים על דפוס ומיתוג', verbose_name='דפוס ומיתוג'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='sizes',
            field=tinymce.models.HTMLField(blank=True, help_text='מידות זמינות למוצר', verbose_name='מידות'),
        ),
    ]
