# Generated by Django 5.2.5 on 2025-11-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_subcategory_fabric_production_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='fabric_production',
            field=models.TextField(blank=True, help_text='אפשרויות ייצור בדים - ניתן להזין HTML', verbose_name='אפשרות ייצור בדים'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='information',
            field=models.TextField(blank=True, help_text='מידע כללי על המוצר - ניתן להזין HTML', verbose_name='מידע'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='marketing_description',
            field=models.TextField(blank=True, help_text='תיאור שיווקי של המוצר - ניתן להזין HTML', verbose_name='תיאור שיווקי'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='pattern_and_branding',
            field=models.TextField(blank=True, help_text='פרטים על דפוס ומיתוג - ניתן להזין HTML', verbose_name='דפוס ומיתוג'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sizes',
            field=models.TextField(blank=True, help_text='מידות זמינות למוצר - ניתן להזין HTML', verbose_name='מידות'),
        ),
    ]
