# Generated by Django 5.2.5 on 2025-11-12 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_subcategory_fabric_production_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, help_text='השאר ריק אם תרצה שהתת-קטגוריה תופיע כקטגוריה בעמוד הראשי', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category', verbose_name='קטגוריה'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='יוצר אוטומטית מהשם', max_length=200, unique=True, verbose_name='Slug'),
        ),
    ]
