# Generated by Django 5.2.16 on 2026-07-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='שם הקמפיין')),
                ('subject', models.CharField(max_length=300, verbose_name='נושא המייל')),
                ('from_name', models.CharField(default='Arye Textile', max_length=120, verbose_name='שם השולח')),
                ('html_content', models.TextField(verbose_name='תוכן HTML')),
                ('status', models.CharField(choices=[('draft', 'טיוטה'), ('sending', 'בשליחה'), ('done', 'הסתיים')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'קמפיין',
                'verbose_name_plural': 'קמפיינים',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='אימייל')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='שם החנות')),
                ('status', models.CharField(choices=[('pending', 'ממתין'), ('sent', 'נשלח'), ('failed', 'נכשל')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'נמען',
                'verbose_name_plural': 'נמענים',
                'ordering': ['id'],
                'unique_together': {('campaign', 'email')},
            },
        ),
    ]
