# Generated by Django 5.2.16 on 2026-07-27 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='אימייל')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='שם החנות')),
                ('status', models.CharField(choices=[('new', 'חדש'), ('contacted', 'נשלח מייל'), ('replied', 'הגיב'), ('in_talks', 'בשיחה'), ('customer', 'לקוח'), ('not_interested', 'לא מעוניין')], default='new', max_length=20, verbose_name='סטטוס')),
                ('notes', models.TextField(blank=True, verbose_name='הערות')),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='פנייה אחרונה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'לקוח',
                'verbose_name_plural': 'לקוחות',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='recipient',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='recipient',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipients', to='campaigns.contact'),
        ),
        migrations.CreateModel(
            name='ContactNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='הערה')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_notes', to='campaigns.contact')),
            ],
            options={
                'verbose_name': 'הערת לקוח',
                'verbose_name_plural': 'הערות לקוח',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(max_length=254, verbose_name='מאת')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='נושא')),
                ('body', models.TextField(blank=True, verbose_name='תוכן')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('received_at', models.DateTimeField(verbose_name='התקבל בתאריך')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='campaigns.contact')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='campaigns.recipient')),
            ],
            options={
                'verbose_name': 'תגובה',
                'verbose_name_plural': 'תגובות',
                'ordering': ['-received_at'],
            },
        ),
    ]
